# Generated by Django 3.2.4 on 2021-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(default='no_picture.png', upload_to='products')),
                ('price', models.FloatField(help_text='in INR rupees')),
                ('created', models.DateField(auto_now_add=True)),
                ('uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
